// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izvdarimvpzxbkmlqopq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6dmRhcmltdnB6eGJrbWxxb3BxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTQyNjgsImV4cCI6MjA1ODkzMDI2OH0.gJYIvN4iYHtGJ5yw2u_wdt-zb74XeNkPDrwJZXbH7Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);